### ISSUE TITLE
Migrate into PL monorepo

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/pl-website-eleventy#23]

**Comment by bmuenzenmeyer** [comment]
@bradfrost spread the word all future development should take place in https://github.com/pattern-lab/patternlab-node under packages/docs

**Comment by bradfrost** [comment]
@bmuenzenmeyer that will be a good addition to the support page: https://pattern-lab-eleventy.netlify.app/support/

Thinking that page will be a good place to say "Changes/bugs regarding the website? Go here. Changes/bugs regarding the product? Go here. And so on"

Thanks for moving this over! Excited for the new site to launch.
