### ISSUE TITLE
Handle PHP in the docs

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/pl-website-eleventy#6]
The current version of PL's website includes full docs for PHP. The new version of PL runs exclusively through Node, but for PHP projects will compile PHP with a PHP renderer. We need to probably:

1. Add a page explaining this
2. Strip out the old PHP language through the docs. For instance:

> "The PHP version of Pattern Lab is being deprecated in favor of a new unified Pattern Lab core. The PHP docs for this topic can be viewed here."

**Comment by QuincyGow** [comment]
Added doc `php-compile.md` which contains the copy from above. 

The following in docs look like they could removed entirely.  Left them in for now but can easily remove as desired:

`advanced-integration-with-compass` 
`advanced-integration-with-grunt`  
`command-prompt-windowslook` 
`pattern-converting` 
`pattern-mobile-view`

PHP docs are still in place.

**Comment by QuincyGow** [comment]
Keeping open.

"These still need worked through from a content perspective, but it's good to get the obsolete PHP references out of there."
