### ISSUE TITLE
Demos page

### ISSUE THREAD

**Issue by bradfrost** [bradfrost/pl-website-eleventy#9]
Carry over this page: https://patternlab.io/demos.html

We'll want to include screenshots of demos, and also link this up to the getting started page and or CLI tool

**Comment by QuincyGow** [comment]
ok

**Comment by QuincyGow** [comment]
Create new template to better display this page.  Grid layout by section.

**Comment by QuincyGow** [comment]
I created a new layout based on `page.njk` but renamed to `demo` and re-directed the content to `<div class="d-layout">` and `<div class="d-layout-item">`.  I'm trying to define the scss in `layout.scss` but the preview in chrome is still defaulting to the `l-container` settings.

**Comment by QuincyGow** [comment]
I created md files for the different demos.  The next step is getting them to list properly on the demos page.  To this point I've been largely taking from the pre-existing templates closest to what I need, and then making necessary tweeks, largely through trial and error.  

Currently I'm looking under the hood of styleguides for an answer. I have not quite found it yet, but I know it's there.   I feel very close to figuring this out but I'm afraid I'm overcomplicating the issue.

Part of me wants to figure this out on my own, but could probably use some help.

**Comment by QuincyGow** [comment]
My browser preview is not updating making it difficult to see my changes.  
Getting this error...

<img width="714" alt="Screen Shot 2020-01-27 at 2 48 47 PM" src="https://user-images.githubusercontent.com/48933977/73208690-e24bef00-4114-11ea-89ea-328f3cd2a3c1.png">

**Comment by bradfrost** [comment]
Closed via #16
